from __future__ import annotations

DEFAULT_APP_CATALOG: tuple[dict[str, object], ...] = (
    {
        "code": "prepaccess",
        "name": "PrepAccess",
        "description": "Authentication, IAM, RBAC, permissions, and audit-friendly security.",
        "category": "core",
        "is_core": True,
    },
    {
        "code": "prepsettings",
        "name": "PrepSettings",
        "description": "Tenant settings, branding, app toggles, and institution configuration.",
        "category": "core",
        "is_core": True,
    },
    {
        "code": "prepstudents",
        "name": "PrepStudents",
        "description": "Student lifecycle, guardians, batches, enrollments, and documents.",
        "category": "learning",
        "is_core": False,
    },
    {
        "code": "preppeople",
        "name": "PrepPeople",
        "description": "Employees, teachers, departments, workload, and staff records.",
        "category": "operations",
        "is_core": False,
    },
    {
        "code": "preplearn",
        "name": "PrepLearn",
        "description": "Courses, modules, lessons, content mapping, and publishing.",
        "category": "learning",
        "is_core": False,
    },
    {
        "code": "prepquestion",
        "name": "PrepQuestion",
        "description": "Question bank, question sets, topics, and AI generation metadata.",
        "category": "learning",
        "is_core": False,
    },
    {
        "code": "prepassess",
        "name": "PrepAssess",
        "description": "Assessments, assignments, evaluations, grading, and results.",
        "category": "learning",
        "is_core": False,
    },
    {
        "code": "prepattend",
        "name": "PrepAttend",
        "description": "Student and employee attendance, corrections, and reports.",
        "category": "operations",
        "is_core": False,
    },
    {
        "code": "preppayroll",
        "name": "PrepPayroll",
        "description": "Salary structures, payroll cycles, payslips, and payment status.",
        "category": "finance",
        "is_core": False,
    },
    {
        "code": "preplive",
        "name": "PrepLive",
        "description": "Live class scheduling, access validation, and live service integration.",
        "category": "learning",
        "is_core": False,
    },
    {
        "code": "prepprogress",
        "name": "PrepProgress",
        "description": "Student progress, teacher tracking, risk scoring, and analytics.",
        "category": "analytics",
        "is_core": False,
    },
    {
        "code": "prepnotify",
        "name": "PrepNotify",
        "description": "Templates, campaigns, preferences, and delivery logs.",
        "category": "communication",
        "is_core": False,
    },
    {
        "code": "prepbilling",
        "name": "PrepBilling",
        "description": "Tenant subscriptions, student subscriptions, invoices, and payments.",
        "category": "finance",
        "is_core": False,
    },
    {
        "code": "prepadmissions",
        "name": "PrepAdmissions",
        "description": "Enquiries, leads, admission pipeline, and trial class booking.",
        "category": "growth",
        "is_core": False,
    },
    {
        "code": "prepcrm",
        "name": "PrepCRM",
        "description": "Communication history, follow-ups, counsellor notes, and retention risk.",
        "category": "growth",
        "is_core": False,
    },
    {
        "code": "prepcontent",
        "name": "PrepContent",
        "description": "Media library, learning resources, foldering, and access control.",
        "category": "content",
        "is_core": False,
    },
    {
        "code": "prepreports",
        "name": "PrepReports",
        "description": "Custom reports, scheduled reports, exports, and report runs.",
        "category": "analytics",
        "is_core": False,
    },
    {
        "code": "prepaudit",
        "name": "PrepAudit",
        "description": "Audit trail, data change history, and system activity.",
        "category": "governance",
        "is_core": True,
    },
    {
        "code": "prepsupport",
        "name": "PrepSupport",
        "description": "Helpdesk tickets, messages, assignments, and SLA tracking.",
        "category": "support",
        "is_core": False,
    },
    {
        "code": "prepmobile",
        "name": "PrepMobile",
        "description": "Mobile app configuration, menus, banners, and release rules.",
        "category": "mobile",
        "is_core": False,
    },
)
